### ISSUE TITLE
Playlist scraping seems broken

### ISSUE THREAD

**Issue by Mythli** [zyrouge/node-youtube-ext#17]
The playlist sample returns

```
error: Failed to parse data from webpage. (TypeError: Cannot read properties of undefined (reading 'split')) at /Users/tobiasanhalt/Development/nations-unite-cli/node_modules/youtube-ext/dist/playlistInfo.js:51:15 at Generator.next (<anonymous>) at fulfilled (/Users/tobiasanhalt/Development/nations-unite-cli/node_modules/youtube-ext/dist/playlistInfo.js:5:58) at processTicksAndRejections (node:internal/process/task_queues:95:5)
printFatalErrorUponExit                               	source-map-support.js:726
process.emit.sharedData.processEmitHook.installedValue	source-map-support.js:753
exit                                                  	per_thread:192
process.emit.sharedData.processEmitHook.installedValue	source-map-support.js:750
(anonymous function)                                  	execution:149
processPromiseRejections                              	promises:288
processTicksAndRejections                             	task_queues:96
```

**Comment by zyrouge** [comment]
Could you give the url for which it fails?
